package br.edu.unijui.dataBase.Interface;;

import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JTable;
import br.edu.unijui.dataBase.DataBase;
import br.edu.unijui.dataBase.Models.Cliente;
import br.edu.unijui.dataBase.Models.ResultSetTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


public class BuscarClientes extends javax.swing.JFrame {

    static private ResultSetTableModel tableModel;
    DataBase db;
    
    private Cliente clienteSelecionado;

    public BuscarClientes() throws SQLException, ClassNotFoundException {
        this.db = new DataBase();
        //define os nomes das colunas da tabela 
        String[] colunas = new String[]{"Cod. Cliente","Nome", "Email", "Telefone"};
        tableModel = new ResultSetTableModel(colunas);
        initComponents();
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTable jTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        novoClienteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(tableModel);
        jTable.setName(""); // NOI18N
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jButton1.setText("Buscar Clientes");
        jButton1.setName("btnExecutar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfNome.setName(""); // NOI18N

        novoClienteButton.setText("Novo Cliente");
        novoClienteButton.setName("btnExecutar"); // NOI18N
        novoClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoClienteButton)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoClienteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:            
            PreparedStatement pstmt = db.getConnection().prepareStatement("select * from clientes where nome like ? order by nome", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            // Setando o valor ao parâmetro 
            if (tfNome.getText().length() > 0) {
              pstmt.setString(1, "%"+tfNome.getText()+"%");
            }else{
              pstmt.setString(1, "%");  
            }

            // Executando a consulta
            ResultSet resultSet = pstmt.executeQuery(); 
            tableModel.setResultSet(resultSet);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
       
        if (evt.getClickCount() == 2) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            Cliente clienteSelecionado = new Cliente();
            clienteSelecionado.setId((int)target.getValueAt(row, 0));
            clienteSelecionado.setNome(target.getValueAt(row, 1).toString());           
            clienteSelecionado.setEmail(target.getValueAt(row, 2).toString());            
            clienteSelecionado.setTelefone(target.getValueAt(row, 3).toString());
            
            // Abra a tela de edição e passe o cliente selecionado como argumento
            EditarCliente editarCliente = new EditarCliente(clienteSelecionado);

            // Você pode exibir a tela de edição como desejar, por exemplo, em um novo JFrame
            JFrame frame = new JFrame("Editar cadastro de cliente");
            frame.setSize(400, 380);
            frame.setContentPane(editarCliente);
            frame.setVisible(true);
           
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void novoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("CadastroCliente");
        frame.setSize(400, 380);
        JPanel panel = new CadastroCliente();
        frame.setContentPane(panel);      
        frame.setVisible(true);
    }//GEN-LAST:event_novoClienteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public Cliente getClienteSelecionado() {
        return clienteSelecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novoClienteButton;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
