/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.unijui.dataBase.Interface;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author gisel
 */
public class Home extends javax.swing.JPanel {
    
    public static void main(String[] args) {
        JFrame frame = new JFrame("Hotel");
        frame.setSize(400, 380);
        JPanel panel = new Home();
        frame.setContentPane(panel);
        frame.setVisible(true);
    }
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientesButton = new javax.swing.JButton();
        quartosButton = new javax.swing.JButton();
        reservasButton = new javax.swing.JButton();

        ClientesButton.setText("Clientes");
        ClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesButtonActionPerformed(evt);
            }
        });

        quartosButton.setText("Quartos");
        quartosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartosButtonActionPerformed(evt);
            }
        });

        reservasButton.setText("Reservas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ClientesButton)
                .addGap(18, 18, 18)
                .addComponent(quartosButton)
                .addGap(18, 18, 18)
                .addComponent(reservasButton)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientesButton)
                    .addComponent(quartosButton)
                    .addComponent(reservasButton))
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesButtonActionPerformed
        // TODO add your handling code here:
          try {
            new BuscarClientes(); 
         } catch (SQLException | ClassNotFoundException ex) {
             Logger.getLogger(EditarCliente.class.getName()).log(Level.SEVERE, null, ex);
         }

    }//GEN-LAST:event_ClientesButtonActionPerformed

    private void quartosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartosButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Quartos");
        frame.setSize(400, 380);
        JPanel panel = new ListaQuartos();
        frame.setContentPane(panel);
        frame.setVisible(true);
    }//GEN-LAST:event_quartosButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientesButton;
    private javax.swing.JButton quartosButton;
    private javax.swing.JButton reservasButton;
    // End of variables declaration//GEN-END:variables
}
